name: Daredakke CI (Kotlin/Android)

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    # daredakke/ フォルダ配下に変更があった時だけ実行
    paths:
      - "daredakke/**"
      - ".github/workflows/daredakke-ci.yml"
  pull_request:
    branches: [main]
    # daredakke/ フォルダ配下に変更があった時だけ実行
    paths:
      - "daredakke/**"
      - ".github/workflows/daredakke-ci.yml"

jobs:
  ########################################
  # Job 1: SAST (CodeQL for Kotlin)
  ########################################
  sast_scan_kotlin:
    name: 1. SAST (CodeQL Kotlin)
    runs-on: ubuntu-latest
    # --- android_lintへの 'needs:' を削除 ---
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
        working-directory: daredakke
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            build-tools;36.0.0
            platforms;android-36
      - uses: github/codeql-action/init@v3
        with:
          languages: "java-kotlin"
          build-mode: manual
      - name: Build Android (for CodeQL)
        # daredakke/ ディレクトリでビルド
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon --stacktrace assembleDebug
      - uses: github/codeql-action/analyze@v3

  ########################################
  # Job 2: SCA (Snyk for Gradle)
  ########################################
  sca_scan_kotlin:
    name: 2. SCA (Snyk Gradle)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # --- android_lintへの 'needs:' を削除 ---
    defaults:
      run:
        shell: bash
        working-directory: daredakke
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle
      - uses: snyk/actions/setup@v4
      - name: Run Snyk (Gradle)
        if: ${{ env.SNYK_TOKEN != '' }}
        continue-on-error: true # ビルドは止めない
        # daredakke/ ディレクトリを指定してスキャン
        run: snyk test --all-sub-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
