name: Go Mod Tidy

on:
  push:
    paths:
      - "backend/go.mod"
      - "backend/go.sum"
  pull_request:
    paths:
      - "backend/go.mod"
      - "backend/go.sum"

jobs:
  go-mod-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0"

      - id: tidy
        name: Run go mod tidy
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            backend/go.mod

      - name: Auto-commit changes
        if: steps.tidy.outputs.tidied == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: go mod tidy"
          file_pattern: "backend/go.*"
